<?php echo phpinfo();

// GLOBAL VARIABLES
// echo $_SERVER["DOCUMENT_ROOT"];
// echo "<br>";
// echo $_SERVER["PHP_SELF"];
// echo "<br>";
// echo $_SERVER["SERVER_NAME"];
// echo "<br>";
// echo $_SERVER["HTTP_HOST"];
// echo "<br>";
// echo $_SERVER["REQUEST_METHOD"];
// echo "<br>";
// echo $_SERVER["QUERY_STRING"];
// echo "<br>";
// echo $_SERVER["HTTP_USER_AGENT"];
// echo "<br>";
// echo $_SERVER["REMOTE_ADDR"];
// echo "<br>";
// echo $_SERVER["SCRIPT_NAME"];
// echo "<br>";
// echo $_SERVER["SCRIPT_FILENAME"];
// echo "<br>";
// echo $_SERVER["SERVER_PORT"];
// echo "<br>";
// echo $_SERVER["SERVER_ADMIN"];
// echo "<br>";
// echo $_SERVER["SERVER_ADDR"];
// echo "<br>";
// echo $_SERVER["SERVER_SOFTWARE"];
// echo "<br>";
// echo $_SERVER["SERVER_PROTOCOL"];
// echo "<br>";
// echo $_SERVER["REQUEST_TIME"];
// echo "<br>";
// echo $_SERVER["REQUEST_TIME_FLOAT"];
// echo "<br>";
// echo $_SERVER["HTTP_REFERER"];
// echo "<br>";
// echo $_SERVER["HTTP_ACCEPT"];
// echo "<br>";
// echo $_SERVER["HTTP_ACCEPT_ENCODING"];
// echo "<br>";
// echo $_SERVER["HTTP_ACCEPT_LANGUAGE"];
// echo "<br>";
// echo $_SERVER["HTTP_CONNECTION"];
// echo "<br>";
// echo $_SERVER["HTTP_COOKIE"];
// echo "<br>";
// echo $_SERVER["HTTP_UPGRADE_INSECURE_REQUESTS"];
// echo "<br>";
// echo $_SERVER["HTTP_CACHE_CONTROL"];
// echo "<br>";
// echo $_GET["name"];
// echo "<br>";
// echo $_GET["age"];
// $_POST["name"];
// $_FILES["file"];
// $_REQUEST["name"];
// $_COOKIE["name"];
// $_SESSION["name"];
// echo $_ENV["USER"];

